### ISSUE TITLE
Question about calibration

### ISSUE THREAD

**Issue by KurokoWD** [ZiwenZhuang/parkour#38]
Thanks to your excellent work!
I would like to know if camera calibration is required. If not, please tell me why.

**Comment by ZiwenZhuang** [comment]
No serious calibration for the camera extrinsic is needed since some domain randomization for the camera extrinsic is applied during distillation.

I set the camera extrinsic by roughly comparing the camera position with the real-world image. Please refer to https://github.com/ZiwenZhuang/parkour/blob/main/legged_gym/legged_gym/envs/base/legged_robot_field.py#L717 for the visualization in simulation.

**Comment by KurokoWD** [comment]
Thanks to your reply
