### ISSUE TITLE
A1 deployment code

### ISSUE THREAD

**Issue by fan-ziqi** [ZiwenZhuang/parkour#5]
May I ask when you will update the A1 deployment code

**Comment by ZiwenZhuang** [comment]
Hi

The deployment code on A1 is similar to Go1, just use the main branch on `unitree_ros_real` and `a1_visual_embedding.py`

However, due to the old hardware and motor performance issues, we will not release checkpoints for A1 for now.

We will update the deployment instructions for A1 soon.

Best,

**Comment by fan-ziqi** [comment]
Thank you for your open source
